version: '3'

services:

  app:
    container_name: creator_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: creator_db
    ports:
      - '5432:5432'
    env_file:
      - .env