version: '3'

services:

  app:
    container_name: creator_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: 8080
      DB_CONN: "postgres://admin:taco@content_creator:5432/content_creator?sslmode=disable"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: creator_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "taco"
      POSTGRES_DB: "content_creator"
      TZ: 'UTC'
      PGTZ: 'UTC'